title: Vitor Stabile Garcia # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  <br>
  My name is Vitor Stabile Garcia and I'm chemical engineer with six years of experience in food industry like manager and developer. 
  I started programming in 2017 using MATLAB language in my Master Degree to simulate chemical process like
  distillation columns, mass transfer and mathematic models.
  <br>
  
  <br>
  Since that date, I started to learn another programming languages like Java, C# and Python and started to develop
  some programs in my area and another areas like engineer production.
  <br>
  
  <a href="https://www.linkedin.com/in/vitor-stabile-garcia-5b151b67">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
