title: Vitor Stabile Garcia # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  My name is Vitor Stabile Garcia and I'm a chemical engineer with six years experience in food industry as manager and developer. 
  I started programming in 2017 using MATLAB language in my Master Degree to simulate chemical process like
  distillation columns, mass transfer and mathematic models.
  <br><br>
  
  Since then, I started to learn another programming languages like Java, C# and Python and I started to develop
  some programs in chemical engineer and other related areas.
  <br><br>
  
  <a href="https://www.linkedin.com/in/vitor-stabile-garcia-5b151b67">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
